### PR TITLE
Removed AWS deploy role and promote it into utility-roles

### PR DESCRIPTION
**Pull request by askldjd**
With PR https://github.com/department-of-veterans-affairs/appeals-deployment/pull/252, aws-deploy role is moved into the appeals-deployment repository.

### CODE REVIEW

**Review by orischwartz — CHANGES_REQUESTED** [review]
@askldjd I'm OK with pulling VA-only functionality out of here and into private repos but as currently configured this PR leaves this repo with a broken dependency in [`deploy-to-aws.yml`](https://github.com/department-of-veterans-affairs/ansible-common-roles/blob/master/deploy-to-aws.yml#L87).

We could remove `deploy-to-aws.yml` too but then that would leave https://github.com/department-of-veterans-affairs/roadrunner-devops with a broken dependency. 

A few options to move forward:

1. Move deploy-to-aws.yml to the VA-only repository
  - Also delete `roadrunner-devops` (is there any value in keeping it? maybe just the docs)
  - Could then consider moving the `roadrunner` and `roadrunner-aws` roles out of here too.
2. Add the launch config cleanup logic to this repo, but default to disable it (e.g, `include: launch-config-cleanup.yml when: remove-old-lc is defined`).

**Comment by askldjd** [comment]
Good catch. I will proceed with Option 1 by moving more stuff out of common-roles.

**Comment by askldjd** [comment]
`deploy-to-aws.yml` has been moved into `appeals-deployment` repo. Also moved `roadrunner` and `roadrunner-aws` as well.

I don't have access to `roadrunner-devops`. So I can't make changes to it. I think we can just update the README to indicate that the repo is deprecated. 

@orischwartz Please re-review.

**Review by orischwartz — APPROVED** [review]

**Comment by orischwartz** [comment]
:+1: LGTM, not sure if it makes sense to leave `aws-bake` in this repo now -- it is of limited value without the other roles.

**Comment by askldjd** [comment]
We can probably do multiple rounds of clean up. I also want to move ruby and nodejs out as well since we are the only consumer of those roles.

**Pull request merged**
